routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\FrontController;


// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/','FrontController@index' );
Route::get('/book/{id}','FrontController@show')->name('frontbook.show');

Route::resource('book','BookController')->middleware('auth');

Route::resource('sale','SaleController');

Route::resource('author','AuthorController');

Route::resource('genre','GenreController');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/logout','HomeController@logout');


Route::post('ckeditor', 'CkeditorFileUploadController@store')->name('ckeditor.upload');

app/Models/Sale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    use HasFactory;
    protected $table ='tbl_sales';
    protected $guarded = [];

    public function book(){
        return $this->belongsTo(Book::class);
    }


}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Sale;

class SaleController extends Controller
{

    public function index()
    {
        $sale = Sale::latest()->get();
        return view('sale.index',compact('sale'));
    }


    public function create()
    {
        $book = Book::orderBy('title','ASC')->get();
        $sale = Sale::all();
        return view('sale.create',compact('book','sale'));
    }


    public function store(Request $request)
    {
        $request->validate([
            'book_id'=>'required',
            'price'=>'numeric|required',
            'customer_name'=>'required',
            'customer_contact_no'=>'string|required|min:10',
            'sales_date'=>'required',
        ]);

        $sale = new Sale();
        $sale->book_id = $request->book_id;
        $sale->price = $request->price;
        $sale->customer_name = $request->customer_name;
        $sale->customer_contact_no = $request->customer_contact_no;
        $sale->sales_date = $request->sales_date;
        $sale->save();

        $request->session()->flash('msg','Data inserted successfully');

        return redirect()->route('sale.index');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $book = Book::orderBy('title','ASC')->get();
        $sale = Sale::findOrFail($id);
        return view('sale.edit',compact('book','sale'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'book_id'=>'required',
            'price'=>'numeric|required',
            'customer_name'=>'required',
            'customer_contact_no'=>'string|required|min:10',
            'sales_date'=>'required',
        ]);

        $sale =Sale::findOrFail($id);
        $sale->book_id = $request->book_id;
        $sale->price = $request->price;
        $sale->customer_name = $request->customer_name;
        $sale->customer_contact_no = $request->customer_contact_no;
        $sale->sales_date = $request->sales_date;
        $sale->save();

        $request->session()->flash('msg','Data updated successfully');
        return redirect()->route('sale.index');
    }


    public function destroy(Request $request,$id)
    {
        $sale = new Sale();
        $sale->destroy($id);

        $request->session()->flash('msg','Data deleted successfully');
    }
}

resources/views/sale/create.blade.php
@extends('layouts.master')
@section('title')
Sale
@endsection
@section('content')
<div class="container">
    @if (session()->has('msg'))
        <div class="alert alert-info" role="alert">
            {{session('msg')}}
          </div>

    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">SALE</h3>
      </div>
      <!-- /.card-header -->


      <!-- form start -->
      <form action="{{route('sale.store')}}" method="post">
        @csrf
        <div class="card-body">
          <div class="form-group">
            <label for="title">Book</label>
            <select name="book_id" class="form-control">
                <option value="" selected disabled>Select Books</option>
                @foreach($book as $books)
                <option value="{{$books->id}}">{{$books->title.'--'.$books->author->full_name}}</option>
                @endforeach
            {{-- <input type="text" name="title" class="form-control" id="title" placeholder="Enter Book Title" value="{{old('title')}}"> --}}
            </select>
          </div>
          <div class="form-group">
            <label for="price">Price</label>
            <input type="number" name="price" class="form-control" id="price" placeholder="Enter Price" value="{{old('price')}}">
          </div>
          <div class="form-group">
            <label for="customer_name">Customer Name</label>
            <input type="text" name="customer_name" class="form-control" id="customer_name" placeholder="Customer Name" value="{{old('customer_name')}}">
          </div>
          <div class="form-group">
            <label for="customer_contact_no">Contact No</label>
            <input type="tel" name="customer_contact_no" class="form-control" id="customer_contact_no" placeholder="012-345-6789"  value="{{old('customer_contact_no')}}">
          </div>
          <div class="form-group">
            <label for="sales_date">Date</label>
            <input type="date" name="sales_date" class="form-control" id="sales_date" value=@php echo date('Y-m-d') @endphp>
          </div>

        </div>


        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{{route('sale.index')}}" class="btn btn-danger">Cancel</a>
        </div>
      </form>
    </div>
    <!-- /.card -->





  </div>
@endsection

resources/views/sale/edit.blade.php
@extends('layouts.master')
@section('title')
Sale
@endsection
@section('content')
<div class="container">

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">EDIT SALE</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form action="{{route('sale.update',$sale->id)}}" method="post">
        @csrf @method('put')
        <div class="card-body">
          <div class="form-group">
            <label for="title">Book Title</label>
           <select name="book_id" class="form-control">
               @foreach($book as $book)
               <option value="{{$book->id}}" {{$book->id == $sale->book_id? 'Selected':''}}>{{$book->title.'--'.$book->author->full_name}}</option>
               @endforeach
           </select>
          </div>
          <div class="form-group">
            <label for="price">Price</label>
            <input type="number" name="price" class="form-control" id="price"  value="{{$sale->price}}">
          </div>
          <div class="form-group">
            <label for="customer_name">Customer Name</label>
            <input type="text" name="customer_name" class="form-control" id="customer_name"  value="{{$sale->customer_name}}">
          </div>
          <div class="form-group">
            <label for="customer_contact_no">Contact No</label>
            <input type="tel" name="customer_contact_no" class="form-control" id="customer_contact_no"  value="{{$sale->customer_contact_no}}">
          </div>
          <div class="form-group">
            <label for="sales_date">Sale Date</label>
            <input type="date" name="sales_date" class="form-control" id="sales_date" value="{{$sale->sales_date}}">
          </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="{{route('sale.index')}}" class="btn btn-danger">Cancel</a>
        </div>
      </form>
    </div>
    <!-- /.card -->





  </div>
@endsection

resources/views/sale/index.blade.php
@extends('layouts.master')
@section('title')
Sale
@endsection
@section('content')
<div class="container">


    @if(Session::has('msg'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ Session::get('msg') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <div class="text-right">
        <a href="{{route('sale.create')}}" class="btn btn-primary">ADD SALE</a>
    </div>


    <div class="card">
      <div class="card-header text-center">
        <h3 class=" text-center">List of Sales</h3>

        {{-- <div class="card-tools">
          {{-- <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div> --}}
        {{-- </div>  --}}
      </div>


      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap" id="myTable">
          <thead>
            <tr>
              <th>ID</th>
              <th>Book Title</th>
              <th>Price</th>
              <th>Customer Name</th>
              <th>Contact No</th>
              <th>Sale Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
              @foreach($sale as $sale)
            <tr>
                <input type="hidden" id="delete_id" name="delete_id" value="{{$sale->id}}">
              <td>{{$loop->index+1}}</td>
              <td>{{$sale->book->id.'--'.$sale->book->author->full_name}}</td>
              <td>{{$sale->price}}</td>
              <td>{{$sale->customer_name}}</td>
              <td>{{$sale->customer_contact_no}}</td>
              <td>{{$sale->sales_date}}</td>
              <td>
                  <form action="{{route('sale.destroy',$sale->id)}}" method="post" >
                    @csrf @method('delete')

                    <a href="{{route('sale.edit',$sale->id)}}" class="btn btn-warning"><i class="fa fa-pencil-alt"></i></a>
                    <button type="submit" id="delete-btn" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                  </form>


              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->

</div>
    <!-- /.card -->
  </div>

  <script>
      $(function(){
        $('#myTable').DataTable();
           $("#delete-btn").on("click",function(e){
            e.preventDefault();
            var delete_id = $("#delete_id").val();

            Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                        }).then((result) => {
                        if (result.isConfirmed) {
                            var data = {
                                "_token":$('meta[name="csrf-token"]').attr('content'),
                                'id':delete_id
                            }
                           $.ajax({
                               type:"DELETE",
                               url:"/sale/" + delete_id,
                               data:data,
                               success:function(response){
                                  location.reload();
                                   Swal.fire(
                                         'Deleted!',
                                         'Your file has been deleted.',
                                        'success'
                                   )
                               }
                           })

                        }
                    });

          });
      });

  </script>
   {{-- @if (Session::has('msg'))
  <script>
      toastr.success("{{!!Session::get('msg')!!}}");
  </script>
   @endif --}}
@endsection