routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\FrontController;


// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/','FrontController@index' );
Route::get('/book/{id}','FrontController@show')->name('frontbook.show');

Route::resource('book','BookController')->middleware('auth');

Route::resource('sale','SaleController');

Route::resource('author','AuthorController');

Route::resource('genre','GenreController');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/logout','HomeController@logout');


Route::post('ckeditor', 'CkeditorFileUploadController@store')->name('ckeditor.upload');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    protected $table ='tbl_books';
    protected $guarded = [];

    public function author()
    {
        return $this->belongsTo(Author::class);
    }
    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use App\Models\Book;
use App\Models\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class BookController extends Controller
{

    public function index()
    {
        $books = Book::latest()->get();
        return view('books.index', compact('books'));
    }

    public function create()
    {
        $author = Author::orderBy('full_name', "ASC")->get();
        $genre = Genre::orderBy('name', 'ASC')->get();
        $books = Book::all();
        return view('books.create', compact('author', 'genre','books'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'author_id' => 'required',
            'genre_id' => 'required',
            'published_date' => 'required',
            'image' => 'required|mimes:jpg,png,jpeg'
        ],
            [
                'title.required' => "Book Title is required",
                'author_id.required' => "Author Name is required",
                'genre_id.required' => "Genre Name is required",
            ]
        );
        $books = new Book();

        $random = Str::random(10);
        if ($request->hasFile('image')) {
            $image_tmp = $request->file('image');
            if ($image_tmp->isValid()) {
                $extension = $image_tmp->getClientOriginalExtension();
                $filename = $random . '.' . $extension;
                $image_path = 'uploads/' . $filename;
                Image::make($image_tmp)->save($image_path);
                $books->image = $filename;
            }
        }

        $books->title = $request->title;
        $books->author_id = $request->author_id;
        $books->summary = $request->summary;
        $books->genre_id = $request->genre_id;
        $books->published_date = $request->published_date;
        $books->save();
        $request->session()->flash('msg', "Data was inserted successfully");
        return redirect()->route('book.index');

    }

    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $books = Book::findOrFail($id);
        $author = Author::orderBy('full_name', "ASC")->get();
        $genre = Genre::orderBy('name', 'ASC')->get();
        return view('books.edit', compact('books', 'author', 'genre'));
    }

    public function update(Request $request, $id)
    {

        $request->validate([
            'title' => 'required',
            'author_id' => 'required',
            'genre_id' => 'required',
            'published_date' => 'required',
            'image' => 'required|mimes:jpg,png,jpeg'

        ],
            [
                'title.required' => "Book Title is required",
                'author_id.required' => "Author Name is required",
                'genre_id.required' => "Genre Name is required",
            ]
        );

        $books = Book::findOrFail($id);

        $random = Str::random(10);
        if ($request->hasFile('image')) {
            $image_tmp = $request->file('image');
            if ($image_tmp->isValid()) {
                $extension = $image_tmp->getClientOriginalExtension();
                $filename = $random . '.' . $extension;
                $image_path = 'uploads/' . $filename;
                Image::make($image_tmp)->save($image_path);
                $books->image = $filename;
            }
        }


        $books->title = $request->title;
        $books->summary = $request->summary;
        $books->author_id = $request->author_id;
        $books->genre_id = $request->genre_id;
        $books->published_date = $request->published_date;
        $books->save();
        $request->session()->flash('msg', "Data was updated successfully");
        return redirect()->route('book.index');
    }

    public function destroy(Request $request, $id)
    {
        $books = new Book();
        $books->destroy($id);
        $request->session()->flash('msg', "Data was deleted successfully");
        // return redirect()->route('book.index');
    }
}

resources/views/books/create.blade.php
@extends('layouts.master')
@section('title')
Sale
@endsection
@section('content')
<div class="container">
    @if (session()->has('msg'))
        <div class="alert alert-info" role="alert">
            {{session('msg')}}
          </div>

    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">ADD BOOKS</h3>
      </div>
      <!-- /.card-header -->


      <!-- form start -->
      <form action="{{route('book.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="title">Book Title</label>
                        <input type="text" name="title" class="form-control" id="title" placeholder="Enter Book Title" value="{{old('title')}}">
                      </div>
                </div>
            </div>
         <div class="row">
             <div class="col-md-6">

                <div class="form-group">
                    <label for="author">Author</label>
                    <select name="author_id" id="" class="form-control">
                        <option value="" selected disabled>Select Author</option>
                        @foreach($author as $author)
                        <option value="{{$author->id}}">{{$author->full_name}}</option>
                        @endforeach
                    </select>
                    {{-- <input type="text" name="author_name" class="form-control" id="author" placeholder="Enter Book Author" value="{{old('title')}}"> --}}
                  </div>
             </div>
             <div class="col-md-6">
                <div class="form-group">
                    <label for="author">Genre</label>
                    <select name="genre_id" id="" class="form-control">
                        <option value="" selected disabled>Select Genre</option>
                        @foreach($genre as $genre)
                        <option value="{{$genre->id}}">{{$genre->name}}</option>
                        @endforeach
                    </select>
                    {{-- <input type="text" name="author_name" class="form-control" id="author" placeholder="Enter Book Author" value="{{old('title')}}"> --}}
                  </div>

             </div>
         </div>

         <div class="row">
             <div class="col-md-12">
                <div class="form-group">
                    <label for="published_date">Published Date</label>
                    <input type="date" max="@php echo date('Y-m-d') @endphp" name="published_date" class="form-control" id="published_date" value=@php echo date('Y-m-d') @endphp>
                  </div>
             </div>
         </div>

         <div class="row">
            <div class="col-md-12">
               <div class="form-group">
                   <label for="image">Image</label>
                   <input type="file"  name="image" class="form-control" id="image"  accept="image/*">
                 </div>

                 {{-- <image src="{{asset('uploads/'.$books->image)}}" style="height:20px, with:20px"></image> --}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
               <div class="form-group">
                   <label for="summary">Summary</label>
                  <textarea name="summary" id="summary" cols="30" rows="10" class="form-control"></textarea>
                 </div>

                 {{-- <image src="{{asset('uploads/'.$books->image)}}" style="height:20px, with:20px"></image> --}}
            </div>
        </div>


        </div>


        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{{route('book.index')}}" class="btn btn-danger">Cancel</a>
        </div>
     </form>
    </div>
    <!-- /.card -->





  </div>

  <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
  <script type="text/javascript">
  CKEDITOR.replace('summary', {
  filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
  filebrowserUploadMethod: 'form'
  });

@endsection

resources/views/books/edit.blade.php
@extends('layouts.master')
@section('title')
    Sale
@endsection
@section('content')
    <div class="container">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">EDIT BOOKS</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="{{ route('book.update', $books->id) }}" method="post" enctype="multipart/form-data">
                @csrf @method('put')
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">Book Title</label>
                                <input type="text" name="title" class="form-control" id="title"
                                    placeholder="Enter Book Title" value="{{ $books->title }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="author">Author</label>
                                <select name="author_id" id="author" class="form-control">
                                    @foreach ($author as $author)
                                        <option value="{{ $author->id }}"
                                            {{ $author->id == $books->author_id ? 'Selected' : '' }}>
                                            {{ $author->full_name }}</option>
                                    @endforeach
                                </select>
                                {{-- <input type="text" name="author_name" class="form-control" id="author" placeholder="Enter Book Author" value="{{$books->author_name}}"> --}}
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="genre">Genre</label>
                                <select name="genre_id" id="genre" class="form-control">
                                    @foreach ($genre as $genre)
                                        <option value="{{ $genre->id }}"
                                            {{ $genre->id == $books->genre_id ? 'Selected' : '' }}>
                                            {{ $genre->name }}</option>
                                    @endforeach
                                </select>
                                {{-- <input type="text" name="author_name" class="form-control" id="author" placeholder="Enter Book Author" value="{{$books->author_name}}"> --}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="published_date">Published Date</label>
                                <input type="date" name="published_date" class="form-control" id="published_date"
                                   max="@php echo date('Y-m-d') @endphp" value="{{ $books->published_date }}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" name="image" accept="image/*" class="form-control" id="image">
                            </div>
                            <img src="{{ asset('uploads/'.$books->image) }}" style="width: 100px" id="one">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                           <div class="form-group">
                               <label for="summary">Summary</label>
                              <textarea name="summary" id="summary" cols="60" rows="10">{{$books->summary}}</textarea>
                             </div>

                             {{-- <image src="{{asset('uploads/'.$books->image)}}" style="height:20px, with:20px"></image> --}}
                        </div>
                    </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{{ route('book.index') }}" class="btn btn-danger">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.card -->





    </div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.master')
@section('title')
Sale
@endsection
@section('content')
<div class="container">


    @if(Session::has('msg'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ Session::get('msg') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <div class="text-right">
        <a href="{{route('book.create')}}" class="btn btn-primary">Add Books</a>
    </div>


    <div class="card">
      <div class="card-header">
        <h3 class="text-center">List of Books</h3>

        <div class="card-tools">
          {{-- <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div> --}}
        </div>
      </div>


      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap" id="myTable">
          <thead>
            <tr>
              <th>ID</th>
              <th>Book Title</th>
              <th>Author</th>
              <th>Genre</th>
              <th>Image</th>
              <th>Published Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
              @foreach($books as $books)
            <tr>
                <input type="hidden" id="delete_id" name="delete_id" value="{{$books->id}}">
              <td>{{$loop->index+1}}</td>
              <td>{{$books->title}}</td>
              <td>{{$books->author->full_name}}</td>
              <td>{{$books->genre->name}}</td>
              <td><image src="{{asset('uploads/'.$books->image)}}" height="40px" width="60px"></image></td>
              <td>{{$books->published_date}}</td>
              <td>
                  <form action="{{route('book.destroy',$books->id)}}" method="post" >
                    @csrf @method('delete')

                    <a href="{{route('book.edit',$books->id)}}" class="btn btn-warning"><i class="fa fa-pencil-alt"></i></a>
                    <button type="submit" id="delete-btn" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                  </form>


              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->

</div>
    <!-- /.card -->
  </div>

  <script>
      $(function(){

          $('#myTable').DataTable();
           $("#delete-btn").on("click",function(e){
            e.preventDefault();
            var delete_id = $("#delete_id").val();

            Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                        }).then((result) => {
                        if (result.isConfirmed) {
                            var data = {
                                "_token":$('meta[name="csrf-token"]').attr('content'),
                                'id':delete_id
                            }
                           $.ajax({
                               type:"DELETE",
                               url:"/book/" + delete_id,
                               data:data,
                               success:function(response){
                                  location.reload();
                                   Swal.fire(
                                         'Deleted!',
                                         'Your file has been deleted.',
                                        'success'
                                   )
                               }
                           })

                        }
                    });

          });
      });

  </script>
   {{-- @if (Session::has('msg'))
  <script>
      toastr.success("{{!!Session::get('msg')!!}}");
  </script>
   @endif --}}
@endsection