routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\FrontController;


// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/','FrontController@index' );
Route::get('/book/{id}','FrontController@show')->name('frontbook.show');

Route::resource('book','BookController')->middleware('auth');

Route::resource('sale','SaleController');

Route::resource('author','AuthorController');

Route::resource('genre','GenreController');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/logout','HomeController@logout');


Route::post('ckeditor', 'CkeditorFileUploadController@store')->name('ckeditor.upload');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;
    protected $table ='tbl_authors';
    protected $guarded = [];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Author;

class AuthorController extends Controller
{

    public function index()
    {
        $author = Author::latest()->get();
        return view('author.index',compact('author'));
    }


    public function create()
    {
        return view('author.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'full_name'=>'required'
        ]);

        $author = new Author();
        $author->full_name = $request->full_name;
        $author->save();
        $request->session()->flash('msg',"Data inserted successfully");
        return redirect()->route('author.index');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $author = Author::findOrFail($id);
        return view('author.edit',compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'full_name'=>'required'
        ]);

        $author = Author::findOrFail($id);
        $author->full_name = $request->full_name;
        $author->save();

        $request->session()->flash('msg',"Author updated successfully");
        return redirect()->route('author.index');
    }


    public function destroy(Request $request,$id)
    {
        $author = new Author();
        $author->destroy($id);
        $request->session()->flash('msg',"Author deleted successfully");

    }
}

resources/views/author/create.blade.php
@extends('layouts.master')
@section('title')
Author
@endsection
@section('content')
<div class="container">
    @if (session()->has('msg'))
        <div class="alert alert-info" role="alert">
            {{session('msg')}}
          </div>

    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">ADD BOOKS</h3>
      </div>
      <!-- /.card-header -->


      <!-- form start -->
      <form action="{{route('author.store')}}" method="post">
        @csrf
        <div class="card-body">
          <div class="form-group">
            <label for="title">Author Name</label>
            <input type="text" name="full_name" class="form-control" id="title" placeholder="Enter Full Name" value="{{old('full_name')}}">
          </div>


        </div>


        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{{route('author.index')}}" class="btn btn-danger">Cancel</a>
        </div>
      </form>
    </div>
    <!-- /.card -->





  </div>
@endsection

resources/views/author/edit.blade.php
@extends('layouts.master')
@section('title')
Author
@endsection
@section('content')
<div class="container">

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">EDIT Author</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form action="{{route('author.update',$author->id)}}" method="post">
        @csrf @method('put')
        <div class="card-body">

          <div class="form-group">
            <label for="author">Author Name</label>
            <input type="text" name="full_name" class="form-control" id="author" placeholder="Enter Book Author" value="{{$author->full_name}}">
          </div>
          {{-- <div class="form-group">
            <label for="published_date">Published Date</label>
            <input type="date" name="published_date" class="form-control" id="published_date" value="{{$books->published_date}}">
          </div> --}}

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="{{route('author.index')}}" class="btn btn-danger">Cancel</a>
        </div>
      </form>
    </div>
    <!-- /.card -->





  </div>
@endsection

resources/views/author/index.blade.php
@extends('layouts.master')
@section('title')
Author
@endsection
@section('content')
<div class="container">


    @if(Session::has('msg'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ Session::get('msg') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <div class="text-right">
        <a href="{{route('author.create')}}" class="btn btn-primary">Add Author</a>
    </div>


    <div class="card">
      <div class="card-header">
        <h3 class="text-center">List of Authors</h3>

        <div class="card-tools">
          {{-- <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div> --}}
        </div>
      </div>


      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap" id="myTable">
          <thead>
            <tr>
              <th>ID</th>

              <th>Author Name</th>

              <th>Action</th>
            </tr>
          </thead>
          <tbody>
              @foreach($author as $author)
            <tr>
                <input type="hidden" id="delete_id" name="delete_id" value="{{$author->id}}">
              <td>{{$loop->index+1}}</td>

              <td>{{$author->full_name}}</td>

              <td>
                  <form action="{{route('author.destroy',$author->id)}}" method="post" >
                    @csrf @method('delete')

                    <a href="{{route('author.edit',$author->id)}}" class="btn btn-warning"><i class="fa fa-pencil-alt"></i></a>
                    <button type="submit" id="delete-btn" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                  </form>


              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->

</div>
    <!-- /.card -->
  </div>

  <script>
      $(function(){

          $('#myTable').DataTable();
           $("#delete-btn").on("click",function(e){
            e.preventDefault();
            var delete_id = $("#delete_id").val();

            Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                        }).then((result) => {
                        if (result.isConfirmed) {
                            var data = {
                                "_token":$('meta[name="csrf-token"]').attr('content'),
                                'id':delete_id
                            }
                           $.ajax({
                               type:"DELETE",
                               url:"/author/" + delete_id,
                               data:data,
                               success:function(response){
                                  location.reload();
                                   Swal.fire(
                                         'Deleted!',
                                         'Your file has been deleted.',
                                        'success'
                                   )
                               }
                           })

                        }
                    });

          });
      });

  </script>
   {{-- @if (Session::has('msg'))
  <script>
      toastr.success("{{!!Session::get('msg')!!}}");
  </script>
   @endif --}}
@endsection